server:
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${ds.db.host}:3306/aeat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${ds.db.username}
    password: ${ds.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  redis:
    host: ${rb.host}
    port: ${rb.port}
    password: ${rb.password}
    database: ${rb.database}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wucheng.aeat
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      wucheng:
        aeat:
          mapper: debug
          service: info
          controller: info
aeat:
  jwt:
    location: ${jwt.location}
    alias: ${jwt.alias}
    password: ${jwt.password}
    tokenTTL: ${jwt.tokenTTL}
